name: 'Build Arch packages'
description: 'Build Arch Linux packages'
runs:
  using: "composite"
  steps:
    # https://github.com/marketplace/actions/checkout
    - name: Checkout repo
      uses: actions/checkout@v3

    # https://github.com/marketplace/actions/cache
    - name: Cache pacman db
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Get current date
      id: date
      shell: bash
      run: echo "TODAY_IS=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Generate version string
      id: versionstring
      shell: bash
      run: echo "THIS_VERSTRING=${{ env.TODAY_IS }}.0.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Get Actions Bot ID
      id: gbid
      shell: bash
      if: github.event_name != 'pull_request'
      run: |
        curl --silent \
        --url https://api.github.com/users/$(printf %s "${ACTIONS_BOT_NAME}"|jq -sRr @uri) \
        --output bot_info.json
        echo "bot-id=$(cat bot_info.json | jq --raw-output '.id')" >> $GITHUB_OUTPUT
